### ISSUE TITLE
Implement energy landscapes and pathways from simulation

### ISSUE THREAD

**Issue by stefsmeets** [GEMDAT-repos/GEMDAT#144]
The goal is to derive from the probability density (of e.g. Li+) a free energy landscape and then use that to trace the lowest energy pathways (direction, tortuosity) that lead to percolation (1D, 2D, 3D) etc.

### TODO

- [x] Convert probability density to free energy: `E = - k * T * ln(P)`. Minima in the free energy should coincide with the maxima in the probability density.
- [ ] Calculate connectivity between (meta)stable positions, e.g.: https://dx.doi.org/10.1021/acs.chemmater.0c03893
- [x] Mimick some of the plots in that paper (Figs. 6-8).
- [x] Calculate barriers (i.e. activation energies)

---

softBV does something similar for crystal structures in CIF format:
- https://scripts.iucr.org/cgi-bin/paper?S2052520618015718
- https://www.dmse.nus.edu.sg/asn/softBVCL.html

**Comment by tfamprikis** [comment]
They do something similar in this paper, see discussion around Figure 3:

https://pubs.acs.org/doi/epdf/10.1021/acsaem.2c02627

they calculate the (Helmholz) free energy from the MD-derived density (note in this case they "normalize" the density by dividing with the max - rho_0 in the paper. afaik this is arbitrary and shouldnt affect the shape of the calculated barrier/pathway; it simply shifts your minimum energy at 0)

However, they do not employ any pathfinding algorithm, they just assume the path is linear between two sites... In this case this works but not in a general case (e.g. argyrodite)

all this to say: we have similar calculations on the same material and can compare directly and possibly quantitatively.

**Comment by tfamprikis** [comment]
I saw you were advancing on this, so I've added a simulation file on the following drive:

https://surfdrive.surf.nl/files/index.php/s/AcED4Uck2cG20y1

this corresponds to a simulation very similar to the ones reported in the paper in my previous comment. So using this the result should be something rather similar to their figure 3.

**Comment by SCiarella** [comment]
> I saw you were advancing on this, so I've added a simulation file on the following drive:
> 
> https://surfdrive.surf.nl/files/index.php/s/AcED4Uck2cG20y1
> 
> this corresponds to a simulation very similar to the ones reported in the paper in my previous comment. So using this the result should be something rather similar to their figure 3.

Thank you this will be very useful! 

However I can only load it using `exception_on_bad_xml=False`, and I get some errors like `trajectory.positions=[]`. Can you double check the sanity of the trajectory?

**Comment by SCiarella** [comment]
Branch #178 now evaluates the best percolating path using Dijkstra's algorithm.
I have included a notebook to show some examples.

**Comment by SCiarella** [comment]
It is now possible to plot the paths over the free energy landscape, similarly to the figure in the references:
![newplot](https://github.com/GEMDAT-repos/GEMDAT/assets/58949181/6a657635-e685-444e-8f2f-9d7a3a893871)

It is also possible to evaluate the free energy along the path:
![output](https://github.com/GEMDAT-repos/GEMDAT/assets/58949181/4b22431a-5c32-4620-b818-f621da0559a8)

The results should be tested using a longer trajectory, in order to obtain better statistic. 
[This notebook](https://github.com/GEMDAT-repos/gemdat-notebooks/blob/main/paths.ipynb) explains how to use the new functionality, with some examples.
