### ISSUE TITLE
Overview of the 10/10/2023 meeting 

### ISSUE THREAD

**Issue by alexandrosvasi** [GEMDAT-repos/GEMDAT#163]
Discussion points: 

- [ ] Flexible code - example Jupyter notebook (anastasia is working on this)
- [ ] Volume extraction upon NPT runs 
- [x] #23
- [x] Density plots (Vesta option and plotly) -> #160 
- [x] Error Implementation method 1 #88 
- [ ] Error Implementation method 2
- [x] #144 
- [ ] #167

Brainstorming on structure collapse upon site shape
- [x] #164 (data will be shared soon)
- [ ] compare if the rotation creates an artifact

**Comment by stefsmeets** [comment]
I'm going to close this issue because most items have been implemented or are in progress. Please make a new issue for any outstanding feature requests.
