### ISSUE TITLE
Plots and visualizations

### ISSUE THREAD

**Issue by stefsmeets** [GEMDAT-repos/GEMDAT#6]
This issue has a list of plots and visualizations that should be implemented.

- [x] Figure 1. Displacement of diffusing element -> #9
- [x] Figure 2. Histogram of displacement of diffusing element -> #9
- [x] Figure 3. Displacement per element  -> #9
- [x] Figure 4. Density of diffusing element (3D) -> #63
- [x] Figure 5. Jumps between sites (3D) -> #61 
- [x] Figure 6. Jumps vs distance -> #48 
- [x] Figure 7. Histogram of vibrational amplitudes with fitted Gaussian -> #11
- [x] Figure 8. Occurance vs frequency -> #11 
- [x] Figure 9. Histogram of jumps vs time -> #61
- [x] Figure 10. Number of cooperative jumps per jump-type combination -> #61 
- [x] Jumps movie -> #70 

### RDF (#57)

- [x] Figure 11. 48h Density vs Distance -> #66
- [x] Figure 12. Transition 48h -> #66
- [x] Figure 13. Transition 48h-48h -> #66

**Comment by stefsmeets** [comment]
After #14 we have access to all the data in the `sim_data.mat` file.

Next is to find some way to load the `sites.mat` file and work through the connected plots.

**Comment by stefsmeets** [comment]
All plots have been implemented! 🎉🎉
