### ISSUE TITLE
Trajectory class

### ISSUE THREAD

**Issue by stefsmeets** [GEMDAT-repos/GEMDAT#67]
I think we should set up a trajectory class which will make it easier to handle the simulation data.

Most that we care about is the Trajectory anyways. The pymatgen trajectory class is somewhat limited for our use-case.

This could also take some of the methods in the vibration/displacements modules (speed, displacements, etc.)

Just writing some ideas here:

```python
class Trajectory:
   _coords: np.ndarray[$time, $site, $xyz]
   structure: pymatgen.core.Structure

   @property
   def n_steps(self):
       # return number of steps after equilibration time

   @property
   def coords(self):
       return self._coords[self.n_steps:, ...]

   def displacements(self, element: list[str] | str | None=None):
       # Return displacements for all / selected elements

   def speed(self, element: list[str] | str | None=None):
       # Return speed for all / selected elements

   def set_equilibration_time(self, equilibration_time):
       # sets starting point for data

   def get_coords_for_element(self, label):
       # replaces diff_coords, which is somewhat poorly named

```

### Todo

- [x] Add some sort of `Trajectory.metadata` attribute to track some sort of global simulation parameters like temperature
- [x] Replace test trajectories by fixtures
- [ ] What makes sense to move from `calculate_all()` to `GemdatTrajectory`?
- [x] Add intuitive method to `Trajectory` to easily get coordinates for diffusing atom
- [ ] Add `Trajectory.from_PymatgenTrajectory`
- [ ] Update readme.md with new API

**Comment by stefsmeets** [comment]
Yes, for sure. I think part of the exercise is to chart out what we need for our code and what we can eventually push to pymatgen.
